apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: greenscale-orchestrator-hpa
  namespace: greenscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: greenscale-orchestrator
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: aws-worker-hpa
  namespace: greenscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aws-worker
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: azure-worker-hpa
  namespace: greenscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: azure-worker
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gcp-worker-hpa
  namespace: greenscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gcp-worker
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
