param(
    [Parameter(Mandatory=$true)]
    [string]$RegistryNamespace,

    [string]$Tag = "v1",

    [string]$OutputPath = ".\k8s\rendered\greenscale-cloud.yaml",

    [switch]$UseLoadBalancer
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Normalize-Prefix {
    param([string]$Prefix)
    $value = $Prefix.Trim()
    while ($value.EndsWith("/")) {
        $value = $value.Substring(0, $value.Length - 1)
    }
    if ([string]::IsNullOrWhiteSpace($value)) {
        throw "RegistryNamespace cannot be empty. Example: yourdockerhubname or 123456789012.dkr.ecr.us-east-1.amazonaws.com"
    }
    return $value
}

$root = Resolve-Path (Join-Path $PSScriptRoot "..")
Set-Location $root

$prefix = Normalize-Prefix $RegistryNamespace
$orchestratorImage = "$prefix/greenscale-orchestrator:$Tag"
$workerImage = "$prefix/greenscale-worker:$Tag"

$files = @(
    ".\k8s\namespace.yaml",
    ".\k8s\configmap.yaml",
    ".\k8s\workers.yaml",
    ".\k8s\orchestrator.yaml",
    ".\k8s\hpa.yaml",
    ".\k8s\observability.yaml"
)

foreach ($file in $files) {
    if (-not (Test-Path $file)) {
        throw "Required manifest was not found: $file"
    }
}

$outputDir = Split-Path $OutputPath -Parent
if ($outputDir -and -not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Force -Path $outputDir | Out-Null
}

$content = New-Object System.Collections.Generic.List[string]
$content.Add("# Generated by scripts/windows_render_cloud_manifests.ps1")
$content.Add("# Image prefix: $prefix")
$content.Add("# Tag: $Tag")
$content.Add("---")

foreach ($file in $files) {
    $text = Get-Content $file -Raw
    $text = $text.Replace("greenscale-orchestrator:dev", $orchestratorImage)
    $text = $text.Replace("greenscale-worker:dev", $workerImage)
    $text = $text.Replace("imagePullPolicy: IfNotPresent", "imagePullPolicy: Always")

    if ($UseLoadBalancer -and $file -eq ".\k8s\orchestrator.yaml") {
        $text = $text -replace "(?m)^  type: ClusterIP\r?$", "  type: LoadBalancer"
    }

    $content.Add($text.Trim())
    $content.Add("---")
}

$content -join "`r`n" | Out-File -FilePath $OutputPath -Encoding utf8

Write-Host "Rendered cloud-ready manifest:" -ForegroundColor Green
Write-Host "  $OutputPath"
Write-Host "Images:"
Write-Host "  $orchestratorImage"
Write-Host "  $workerImage"
if ($UseLoadBalancer) {
    Write-Host "The orchestrator Service was rendered as type LoadBalancer." -ForegroundColor Yellow
}
else {
    Write-Host "The orchestrator Service remains ClusterIP. Use kubectl port-forward to access it." -ForegroundColor Yellow
}
